### ISSUE TITLE
Not working on Vue 3 + Ionic

### ISSUE THREAD

**Issue by moxandlotus** [adi518/vue-facebook-login#63] opened 2020-12-28 05:34 UTC
Uncaught (in promise) TypeError: Cannot read property '_c' of undefined

**Comment by adi518** [comment] 2020-12-29 13:46
I didn't test it in Vue 3 yet, so no surprise it doesn't work. If you can provide a repro, I can fix it faster.

**Comment by jakubkoje** [comment] 2021-01-23 17:45
Any new updates on Vue 3 support?

**Comment by adi518** [comment] 2021-01-23 17:53
No. I haven't tested it yet. He's also complaining about Ionic, so we don't know where the issue exactly is, and he didn't bother to provide a repro.

**Comment by jakubkoje** [comment] 2021-01-23 21:43
I could try to reproduce it and create a repo for it. In my opinion, it is because of Vue 3. Ionic shouldn't be an issue.

**Comment by adi518** [comment] 2021-01-23 23:33
I hold the same opinion. A repro will move things faster.

**Comment by jakubkoje** [comment] 2021-01-24 18:56
https://github.com/jakubkoje/vue-facebook-login-vue3-issue

**Comment by adi518** [comment] 2021-01-24 22:57
Cool, I fixed the error, but it still needs work, because some API changed between version 2 and 3. That's going to take more time, but hopefully Vue 3 is backwards-compatible, which means I can support both by adding version 3 APIs instead of replacing them, which will break it for version 2 apps.

**Comment by Startouf** [comment] 2021-04-18 14:37
Hello, any news regarding Vue 3 compatibility ?

**Comment by adi518** [comment] 2021-04-18 19:28
I just did a whole library with Vue 3, so I now know how to fix it, but I'll likely to release it under a new tag that is `vue-facebook-login-component@next` or something.

**Comment by PrashantKapila** [comment] 2021-05-05 04:43
> I just did a whole library with Vue 3, so I now know how to fix it, but I'll likely to release it under a new tag, namely `vue-facebook-login-component@next`. Hopefully, I can pull it off this week.

Hello, any update regarding Vue 3 compatibility

**Comment by bustardo** [comment] 2021-05-05 21:59
Looking forward to this Vue 3 fix, this will save me so much time! Thanks in advance.

**Comment by adi518** [comment] 2021-05-06 17:54
I'm on it. It requires an infra change of moving to [Vite.js](https://vitejs.dev/guide/build.html#library-mode).

**Comment by adi518** [comment] 2021-05-06 21:41
Getting there, plus some other fixes:

![image](https://user-images.githubusercontent.com/12032248/117368923-e0064200-aecc-11eb-892f-3db037e9441d.png)

**Comment by gustawdaniel** [comment] 2021-05-13 10:56
I am presenting some research:

There is article with huge amount of code that shows how to implement fb login in vue3:

https://jasonwatmore.com/post/2020/10/06/vue-3-facebook-login-tutorial-example#index-html

This code in codesandbox

https://codesandbox.io/s/vue-3-facebook-login-example-l9tkc?from-embed

The same content but published in other place

https://morioh.com/p/f58c8fac4343

For analogical package with google login there is similar problem with vue 3

https://github.com/rmartide/vue-google-login/issues/23

**Comment by adi518** [comment] 2021-05-13 13:29
Thanks, @gustawdaniel, but it's almost ready now. I have some technical issues with the Vue 3 component build and preventing the extraction of CSS. Once it's resolved, I will release this new version.

**Comment by adi518** [comment] 2021-05-14 16:41
Ok, it's finally released! I have released it under a new namespace `vue-facebook-login-component-next`, so it won't collapse with the current one. I wish we could keep just one namespace, but since the API used in this package is not backward-compatible - we can't.

Notice you must import its CSS, at least until I find a way to prevent CSS extraction with Vite:
```js
import FacebookLogin from 'vue-facebook-login-component-next'
import 'vue-facebook-login-component-next/dist/style.css'
```

**Closed** 2021-05-14 18:34 UTC
